[storage]
[storage.documents]
name = "documents"
public = false
allowed_mime_types = ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "text/plain"]
file_size_limit = "10MB"
allowed_extensions = ["pdf", "doc", "docx", "txt"]

[[storage.documents.policies]]
name = "Users can upload their own documents"
definition = "auth.uid() = owner"
operation = "INSERT"

[[storage.documents.policies]]
name = "Users can view their own documents"
definition = "auth.uid() = owner"
operation = "SELECT"

[[storage.documents.policies]]
name = "Users can update their own documents"
definition = "auth.uid() = owner"
operation = "UPDATE"

[[storage.documents.policies]]
name = "Users can delete their own documents"
definition = "auth.uid() = owner"
operation = "DELETE"

