// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzvalmxbbozhbiamsnzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dmFsbXhiYm96aGJpYW1zbnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODAwMjUsImV4cCI6MjA3MjA1NjAyNX0.GljsR1exfPCId7bMbiCHjEYn75ou6lqEdkVaoeBwKaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});